# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '5140Assignment3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NMSSH'
  # Pods for 5140Assignment3
  pod 'Firebase/Analytics'

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVision'
  pod 'Firebase/Core'



end
